spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

api:
  security:
    token:
      secret: ${JWT_SECRET:pCmUdLQqOiuezLWfNvwZx4mlWmfgHuadifP13iRoJBLoNP7b1AT1yo8OFYVv8aGPaYowOMzrsmbC4s0OmQ6Jt2}
      expiration-hours: ${JWT_EXPIRATION_HOURS:2}
